// TRANSLATING AN OVERPASS SELECTOR INTO A QUERY AGAINST OUR OWN INDEX.
//
// lib/niche.ts speaks Overpass, because that is what discovery has always used. Its
// filters are raw tag expressions:
//
//   "shop"="bakery"
//   "shop"="bakery"]["name"~"gluten",i          a category narrowed by business name
//   "amenity"="restaurant"]["cuisine"~"sushi",i a category narrowed by another tag
//   "shop"~".*"]["name"~"locksmith",i           any shop whose name matches
//
// The index stores the same tags as jsonb, so the same questions are answerable, but
// the syntax has to be translated rather than passed through.
//
// WHY PARSE RATHER THAN REFACTOR. The obvious alternative is to make resolveNiche
// return a structured shape and have both sources read it. That is the better end
// state and it touches the catalog, both existing sources, the route, the sample and
// the diagnostics. Parsing a syntax WE generate, whose every shape is produced by
// twenty lines of our own code, is a smaller and more reversible step, and it keeps
// the live path byte-identical while the index is unproven.
//
// The parser is deliberately strict: an expression it does not recognise returns null
// and the caller falls back to the live source. A filter half-understood would query
// the index for something subtly different from what the customer asked for, and they
// would have no way to tell.

export type IndexFilter = {
  /** The tag key, e.g. "shop". */
  key: string;
  /** The exact tag value, or null when the selector accepts any value (`~".*"`). */
  value: string | null;
  /** A secondary constraint, e.g. name or cuisine matching a regex. */
  extra: { key: string; pattern: string } | null;
};

/**
 * Parse one Overpass expression as generated by lib/niche.ts.
 *
 * Returns null for anything outside the shapes that file produces, which is the signal
 * to use the live source instead of guessing.
 */
export function parseFilter(raw: string): IndexFilter | null {
  const s = raw.trim();

  // The primary term is always `"key"="value"` or `"key"~"regex"`.
  const head = /^"([a-z_:]+)"(=|~)"([^"]*)"/i.exec(s);
  if (!head) return null;

  const [, key, op, val] = head;
  // `~".*"` is "this tag exists with any value", which is how the generic fallback
  // asks for "any shop". Any OTHER regex on the primary key is not a shape we emit,
  // and quietly treating it as an exact value would be wrong.
  let value: string | null;
  if (op === "=") value = val;
  else if (val === ".*") value = null;
  else return null;

  const rest = s.slice(head[0].length);
  if (rest === "") return { key, value, extra: null };

  // The secondary term, e.g. `]["name"~"gluten",i`. Case-insensitive is the only
  // modifier niche.ts emits.
  const tail = /^\]\["([a-z_:]+)"~"([^"]*)",i$/i.exec(rest);
  if (!tail) return null;

  return { key, value, extra: { key: tail[1], pattern: tail[2] } };
}

/** Parse a whole filter set, or give up if ANY term is unrecognised. */
export function parseFilters(raws: string[]): IndexFilter[] | null {
  const out: IndexFilter[] = [];
  for (const raw of raws) {
    const f = parseFilter(raw);
    // All or nothing. Serving a partial translation would silently narrow the search
    // and look like thin coverage rather than a bug.
    if (!f) return null;
    out.push(f);
  }
  return out.length ? out : null;
}

/**
 * A Postgres regex that means what the Overpass one meant.
 *
 * Overpass regexes are POSIX-ish and so is Postgres's `~*`, so the common cases (a
 * word, an alternation) carry over unchanged. What does NOT carry over is a pattern
 * containing characters Postgres reads as syntax, and niche.ts already escapes its
 * inputs, so anything exotic arriving here is a sign the shape changed.
 */
export function safePattern(pattern: string): string | null {
  if (!pattern || pattern.length > 200) return null;
  // Letters, digits, spaces, alternation and the escapes niche.ts emits. Anything
  // else is refused rather than sent to the database.
  if (!/^[\w\s|.\\'&-]+$/.test(pattern)) return null;
  return pattern;
}
